### ISSUE TITLE
build-remote expects a path instead of an expression

### ISSUE THREAD

**Issue by soenkehahn** [zalora/upcast#36]
`upcast build-remote --help` says that it expects a nix-expression, but it seems to be expecting a file that contains a nix-expression. E.g.
```
upcast build-remote -t host 'import ./default.nix'
```
results in
```
upcast: import default.nix: canonicalizePath: does not exist (No such file or directory)
```
But `upcast build-remote -t host default.nix` seems to work.

**Comment by proger** [comment]
Thanks! I've tweaked that help message.
