### ISSUE TITLE
Generated files should be sorted

### ISSUE THREAD

**Issue by fmap** [zalora/upcast#38]
This'd give us cleaner diffs when new infrastructure is provisioned. `ssh_config` and `store.json`.

Cc: @4z3

**Comment by ip1981** [comment]
I would be much simpler than awk :-)

**Comment by fmap** [comment]
For the interim:
```
awk '/^Host/{X=$0;r[X]="";next}(NF){r[X]=r[X] $0 "\n"} END{ PROCINFO["sorted_in"] = "@ind_str_asc"; for (x in r) { print x; print r[x] }}’
```

**Comment by proger** [comment]
https://github.com/zalora/upcast/pull/42
