### ISSUE TITLE
Security groups are miscompared when one allowance is granted to multiple address ranges.

### ISSUE THREAD

**Issue by fmap** [zalora/upcast#60]
When updating security groups, our [`Rule`](https://github.com/zalora/upcast/blob/09caa2c81be724e16b4603de35259a8efec9d679/src/Upcast/Infra/NixTypes.hs#L243-L250)s are [coerced](https://github.com/zalora/upcast/blob/09caa2c81be724e16b4603de35259a8efec9d679/src/Upcast/Infra/Types/Resource.hs#L250-L254) into Amazonka [`IPPermission`](https://github.com/brendanhay/amazonka/blob/694fc9786ea1765733a224b95f5eaf79646d53f6/amazonka-ec2/gen/Network/AWS/EC2/Types/Product.hs#L2276-L2283)s and [compared with upstream responses](https://github.com/zalora/upcast/blob/09caa2c81be724e16b4603de35259a8efec9d679/src/Upcast/Infra/Types/Resource.hs#L276). Fleas arise when upstream rules authorise a given port to multiple CIDRs, as `IPPermission` will carry the "two" `Rule`s in one value, failing our `converge` diff. An easy fix is to strongly normalise `IPPermission` responses before comparison; `concatMap (undefined :: IPPermission -> [IPPermission])` or so.

@denisshevchenko intends to fix this, consult him should you like it instead.

**Comment by denisshevchenko** [comment]
https://github.com/zalora/upcast/pull/61/files

**Comment by fmap** [comment]
:+1:
