### ISSUE TITLE
allow providing a public key to import into ec2

### ISSUE THREAD

**Issue by phunehehe** [zalora/upcast#62]
it looks like, right now the only way to create an ec2 key is to generate a public key from a private key
importing an existing public key without the private key would be useful

**Comment by fmap** [comment]
Yeah, deriving them from private keys is a bit too assumptive.

**Comment by fmap** [comment]
In the mean time you might get away with writing cloud-init compatible user data, through https://github.com/zalora/upcast/blob/master/nix/aws/ec2-instance.nix#L137-L145.

**Comment by proger** [comment]
Importing is the only supported scenario: https://github.com/zalora/upcast/blob/master/src/Upcast/Infra/Types/Resource.hs#L404

**Comment by phunehehe** [comment]
I realized I was being confusing. Updated.
What I meant is, if the only use of the private key is to generate the public key, why not let the user submit the public key instead?

**Comment by proger** [comment]
That's a nice catch, earlier versions of upcast used that info to manage ssh key agent for you, this is no longer the case.
