### ISSUE TITLE
bootstrap/nix-install deviation from upstream no longer needed?

### ISSUE THREAD

**Issue by phunehehe** [zalora/upcast#64]
`nix-install` seems to be taken from https://github.com/proger/nix-adhoc/blob/c8967ffe6b391a6eb0afffad32ad82eab6c62070/nix-install, of which the only traceable difference from upstream https://github.com/NixOS/nixos-homepage/blob/master/nix/install.in is https://github.com/proger/nix-adhoc/commit/c8967ffe6b391a6eb0afffad32ad82eab6c62070.

IIUC the crux of the commit is the removal of the `-C` flag of curl. Now that the `-C` is not in the upstream version anymore, is there still a need for this customized script?

**Comment by proger** [comment]
this is the reason for bootstrap/nix-install: https://github.com/proger/nix-adhoc/blob/c8967ffe6b391a6eb0afffad32ad82eab6c62070/nix-install#L49-L53

**Comment by phunehehe** [comment]
alright, cool
